<div dir = "rtl"> 

# **بسم الله الرحمن الرحیم**

</div>

<h3 style="direction: rtl; text-align: right;">بردار ستونی</h3>

<p style="direction: rtl; text-align: right;">
به‌ازای یک ماتریس  A ، هرگاه فقط یک ستون داشته باشیم، به آن <strong>بردار ستونی</strong> یا به اختصار «بردار p بعدی» می‌گوییم.
نمایش آن به صورت زیر است:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
A =
\begin{bmatrix}
a_1 \\
\vdots \\
a_p
\end{bmatrix}
$$

</div>

<hr>

<h3 style="direction: rtl; text-align: right;">بردار سطری</h3>

<p style="direction: rtl; text-align: right;">
به‌ازای یک ماتریس، اگر فقط یک <strong>سطر</strong> داشته باشیم، به آن <strong>بردار سطری</strong> یا «بردار q بعدی» گفته می‌شود.  
نمایش آن:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
A' = (a_1, \ldots, a_q)
$$

</div>

<hr>

<h3 style="direction: rtl; text-align: right;">ماتریس مثلثی پایین</h3>

<p style="direction: rtl; text-align: right;">
ماتریس مربعی‌ای را <strong>مثلثی پایین</strong> می‌نامیم که تمام اعضای <strong>بالای قطر اصلی</strong> آن صفر باشند.  
به بیان دیگر، برای ماتریس:

$$ A = (a_{ij})_{p \times p} $$

</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
a_{ij} = 0 \quad \text{if} \; j > i
$$
</div>

<p style="direction: rtl; text-align: right;">
نمایش کلی یک ماتریس مثلثی پایین به صورت زیر است:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
\begin{bmatrix}
\cdot & 0 & 0 & \cdots & 0 \\
\cdot & \cdot & 0 & \cdots & 0 \\
\cdot & \cdot & \cdot & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & 0 \\
\cdot & \cdot & \cdot & \cdots & \cdot
\end{bmatrix}
$$

</div>

<hr>

<h3 style="direction: rtl; text-align: right;">ماتریس مثلثی بالا</h3>

<p style="direction: rtl; text-align: right;">
ماتریس مربعی‌ای را <strong>مثلثی بالا</strong> می‌نامیم که تمام اعضای <strong>زیر قطر اصلی</strong> آن صفر باشند.  
یعنی:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
a_{ij} = 0 \quad \text{if} \; i > j
$$
</div>

<p style="direction: rtl; text-align: right;">
نمایش کلی یک ماتریس مثلثی بالا:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
\begin{bmatrix}
\cdot & \cdot & \cdot & \cdots & \cdot \\
0 & \cdot & \cdot & \cdots & \cdot \\
0 & 0 & \cdot & \cdots & \cdot \\
\vdots & \vdots & \vdots & \ddots & \cdot \\
0 & 0 & 0 & \cdots & \cdot
\end{bmatrix}
$$
</div>


<p style="direction: rtl; text-align: right;">
قبلاً دربارهٔ نحوهٔ نگاه کامپیوتر به ماتریس‌ها صحبت کرده‌ایم.  
حالا با فرض اینکه درس قبلی را خوب مطالعه کرده‌اید پیش می‌رویم.
</p>

<p style="direction: rtl; text-align: right;">
اگر بخواهیم ماتریس‌هایی را که در این فصل معرفی کردیم با «پایتون خام» پیاده‌سازی کنیم، برای هرکدام باید الگوریتم جداگانه‌ای بنویسیم و سپس آن را به کد تبدیل کنیم.  
اما خوشبختانه وقتی از کتابخانهٔ <strong>NumPy</strong> استفاده می‌کنیم، کارمان بسیار راحت‌تر می‌شود.
</p>

<p style="direction: rtl; text-align: right;">
البته اینکه شما هر ماتریس را خودتان با پایتون خام پیاده‌سازی کنید، کار بسیار ارزشمندی‌ست؛ چون باعث می‌شود برنامه‌نویسی را عمیق‌تر یاد بگیرید و ذهن الگوریتمی‌تان تقویت شود.  
اما هدف ما در این کتاب، یادگیری «جبر خطی» با کمک پایتون است؛ نه نوشتن همه‌چیز از صفر.  
به همین دلیل، از این مرحله به بعد از توانایی‌های NumPy کمک می‌گیریم.
</p>

<p style="direction: rtl; text-align: right;">
قبل از اینکه سراغ کدنویسی برویم، اجازه بدهید چند تابع برای مباحثی که تا الان مطرح کردیم از NumPy را معرفی کنم؛ توابعی که قرار است زندگی ما را راحت‌تر کنند! 😊  
این چهار تابع عبارت‌اند از:
</p>

<p style="direction: rtl; text-align: right;">
<strong>arange، reshape، tril، triu</strong>
</p>

<h4 style="direction: rtl; text-align: right;">۱) تابع <code>np.arange</code></h4>

<p style="direction: rtl; text-align: right;">
تابع <code>np.arange</code> یک دنبالهٔ عددی پشت‌سرهم تولید می‌کند.  
</p>

<p style="direction: rtl; text-align: right;">
مثال واقعی برای استفاده در جبر خطی:
</p>
<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
# ساخت ماتریس سطری با اعداد 1 تا 9  
A = np.arange(1, 10)
</p>

<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
# یا ساخت ماتریس 3×3 با اعداد 1 تا 9
A = np.arange(1, 10).reshape(3, 3)
</p>

<hr>

<h4 style="direction: rtl; text-align: right;">۲) تابع <code>reshape</code></h4>

<p style="direction: rtl; text-align: right;">
در جبر خطی، ابعاد بسیار مهم‌اند.  
مثلاً یک بردار باید شکل <span dir="ltr">(n, 1)</span> داشته باشد و یک ماتریس 3×3 باید دقیقاً 3 سطر و 3 ستون داشته باشد.
</p>

<p style="direction: rtl; text-align: right;">
تابع <code>reshape</code> دقیقاً برای «تبدیل ابعاد داده‌ها» استفاده می‌شود.  
داده‌ها همان هستند، اما ساختارشان عوض می‌شود؛ چیزی که در جبر خطی مدام نیاز داریم.
</p>

<ul style="direction: rtl; text-align: right;">
  <li>ساخت بردار ستونی از یک آرایه -> <span dir="ltr">(n -> n×1)</span></li>
  <li>ساخت بردار سطری -> <span dir="ltr">(n -> 1×n)</span></li>
  <li>ساخت ماتریس مربعی -> <span dir="ltr">(n² -> n×n)</span></li>
</ul>

<p style="direction: rtl; text-align: right;">
مثال واقعی:
</p>

<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
v = np.arange(1, 4)          # [1 2 3]  <br>
col = v.reshape(3, 1)        # بردار ستونی1×3  
</p>

<hr>

<h4 style="direction: rtl; text-align: right;">۳) تابع <code>np.tril</code></h4>

<p style="direction: rtl; text-align: right;">
در جبر خطی، ماتریس‌های «مثلثی پایین» داشتیم؛  
</p>

<p style="direction: rtl; text-align: right;">
تابع <code>np.tril</code> برای ساخت چنین ماتریس‌هایی استفاده می‌شود.  
این تابع از یک ماتریس مربعی یک نسخهٔ مثلثی پایین تولید می‌کند:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>همهٔ عناصر بالا صفر می‌شوند -> <span dir="ltr">(j > i)</span></li>
  <li>فقط قطر و عناصر زیر قطر باقی می‌مانند</li>
</ul>

<p style="direction: rtl; text-align: right;">
مثال:
</p>

<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
A = np.arange(1, 10).reshape(3, 3)  <br>
L = np.tril(A)
</p>

<hr>

<h4 style="direction: rtl; text-align: right;">۴) تابع <code>np.triu</code></h4>

<p style="direction: rtl; text-align: right;">
ماتریس‌های «مثلثی بالا» را نیز میتوان با دستور ساده‌ایی پیاده سازی کرد.  
</p>

<p style="direction: rtl; text-align: right;">
تابع <code>np.triu</code> از یک ماتریس مربعی نسخهٔ مثلثی بالا می‌سازد:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>عناصر زیر قطر صفر می‌شوند -> <span dir="ltr">(i > j)</span></li>
  <li>فقط قطر و عناصر بالای آن باقی می‌مانند</li>
</ul>

<p style="direction: rtl; text-align: right;">
مثال:
</p>

<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
A = np.arange(1, 10).reshape(3, 3)  <br>
U = np.triu(A)
</p>


<table style="width: 100%; border-collapse: collapse; direction: rtl; text-align: right; font-size: 16px;">
  <tr style="background-color: #3a3a3a; color: #e4e4e4;">
    <th style="padding: 10px; border: 1px solid #555;">تابع</th>
    <th style="padding: 10px; border: 1px solid #555;">کاربرد در جبر خطی</th>
    <th style="padding: 10px; border: 1px solid #555;">نمونهٔ استفاده</th>
  </tr>

  <tr>
    <td style="padding: 10px; border: 1px solid #ccc;"><code>np.arange</code></td>
    <td style="padding: 10px; border: 1px solid #ccc;">
      ساخت دنبالهٔ منظم اعداد برای تولید بردار و ماتریس‌های پایه
    </td>
    <td style="padding: 10px; border: 1px solid #ccc; direction: ltr; text-align: left;">
      np.arange(1, 10)
    </td>
  </tr>

  <tr>
    <td style="padding: 10px; border: 1px solid #ccc;"><code>reshape</code></td>
    <td style="padding: 10px; border: 1px solid #ccc;">
      تبدیل آرایهٔ خطی به ماتریس یا بردار با ابعاد دلخواه
    </td>
    <td style="padding: 10px; border: 1px solid #ccc; direction: ltr; text-align: left;">
      np.arange(1, 10).reshape(3, 3)
    </td>
  </tr>

  <tr>
    <td style="padding: 10px; border: 1px solid #ccc;"><code>np.tril</code></td>
    <td style="padding: 10px; border: 1px solid #ccc;">
      ساخت ماتریس مثلثی پایین 
    </td>
    <td style="padding: 10px; border: 1px solid #ccc; direction: ltr; text-align: left;">
      np.tril(A)
    </td>
  </tr>

  <tr>
    <td style="padding: 10px; border: 1px solid #ccc;"><code>np.triu</code></td>
    <td style="padding: 10px; border: 1px solid #ccc;">
      ساخت ماتریس مثلثی بالا 
    </td>
    <td style="padding: 10px; border: 1px solid #ccc; direction: ltr; text-align: left;">
      np.triu(A)
    </td>
  </tr>
</table>


<h3 style="direction: rtl; text-align: right;">تمرین‌های کاربردی با توابع NumPy</h3>

<p style="direction: rtl; text-align: right;">
در این بخش چند تمرین عملی طراحی کرده‌ام که مستقیماً از توابع <code>arange</code>، <code>reshape</code>، <code>tril</code> و <code>triu</code> استفاده می‌کنند و برای تمرین کدنویسی میتوانند مفید باشند.
</p>

<hr>

<h4 style="direction: rtl; text-align: right;">تمرین ۱: ساخت ماتریس 3×4 با اعداد پشت‌سرهم</h4>

<p style="direction: rtl; text-align: right;">
یک ماتریس 3×4 بسازید که درایه‌های آن از 1 تا 12 به ترتیب پر شده باشند.  
این تمرین برای درک ترکیب <code>np.arange</code> و <code>reshape</code> مناسب است.
</p>

<p style="direction: rtl; text-align: right;">
ایده:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>اول یک آرایهٔ 1بعدی از 1 تا 12 با <code>np.arange</code> بسازید.</li>
  <li>بعد آن را با <code>reshape</code> به ماتریس 3×4 تبدیل کنید<br> ازتان میخوام که قبل از اینکه کد جواب را ببینید اول خودتان یک تلاشی در جهت حل سوال بکنید.</li>
</ul>

In [10]:
import numpy as np

# تمرین 1: ساخت ماتریس 3×4 با اعداد 1 تا 12

# ساخت آرایه 1بعدی از 1 تا 12
nums = np.arange(1, 13)

# تبدیل به ماتریس 3×4
A = nums.reshape(3, 4)

print("matrix A (3×4):")
print(A)

matrix A (3×4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<hr>

<h4 style="direction: rtl; text-align: right;">تمرین ۲: ساخت بردار ستونی و بردار سطری</h4>

<p style="direction: rtl; text-align: right;">
یک بردار ستونی 5بعدی و یک بردار سطری 5بعدی با درایه‌های 1 تا 5 بسازید.  
در این تمرین تمرکز روی نحوهٔ کنترل شکل آرایه‌ها در جبر خطی است.
</p>

<p style="direction: rtl; text-align: right;">
ایده:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>با <code>np.arange</code> اعداد 1 تا 5 را می‌سازیم.</li>
  <li>برای بردار ستونی: شکل را به <span dir="ltr">(5, 1)</span> تغییر می‌دهیم.</li>
  <li>برای بردار سطری: شکل را به <span dir="ltr">(1, 5)</span> تغییر می‌دهیم.</li>
</ul>

In [1]:
import numpy as np

# تمرین 2: بردار ستونی و سطری 5بعدی

v = np.arange(1, 6)  # آرایه 1بعدی: [1 2 3 4 5]

col_vec = v.reshape(5, 1)  # بردار ستونی (5×1)
row_vec = v.reshape(1, 5)  # بردار سطری (1×5)

print("بردار ستونی (1×5):")
print(col_vec)
print("shape:", col_vec.shape)

print("\nبردار سطری (5×1):")
print(row_vec)
print("shape:", row_vec.shape)

بردار ستونی (1×5):
[[1]
 [2]
 [3]
 [4]
 [5]]
shape: (5, 1)

بردار سطری (5×1):
[[1 2 3 4 5]]
shape: (1, 5)


<hr>

<h4 style="direction: rtl; text-align: right;">تمرین ۳: ساخت ماتریس مثلثی پایین از یک ماتریس دلخواه</h4>

<p style="direction: rtl; text-align: right;">
یک ماتریس مربعی 4×4 بسازید که درایه‌های آن از 1 تا 16 به ترتیب پر شده‌اند، سپس از روی آن ماتریس مثلثی پایین استخراج کنید.  
</p>

<p style="direction: rtl; text-align: right;">
ایده:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>با <code>np.arange</code> و <code>reshape</code> یک ماتریس 4×4 می‌سازیم.</li>
  <li>با <code>np.tril</code> تبدیلش میکنیم به پایین مثلثی.</li>
</ul>

In [12]:
import numpy as np

# تمرین 3: ماتریس مثلثی پایین

# ساخت ماتریس 4×4 با اعداد 1 تا 16
A = np.arange(1, 17).reshape(4, 4)

print("ماتریس A:")
print(A)

# استخراج قسمت مثلثی پایین
L = np.tril(A)

print("\nماتریس مثلثی پایین L:")
print(L)

ماتریس A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

ماتریس مثلثی پایین L:
[[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]
